let images = [
  {"url": "img/photos/ca01.jpg", "label": "foster city, ca, 2017"},
  {"url": "img/photos/ca02.jpg", "label": "rancho san antonio, ca, 2017"},
  {"url": "img/photos/ca03.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/ca04.jpg", "label": "san francisco international airport, ca, 2017"},
  {"url": "img/photos/ca05.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/ca06.jpg", "label": "devil's slide, ca, 2017"},
  {"url": "img/photos/ca07.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/ca08.jpg", "label": "san francisco international airport, ca, 2017"},
  {"url": "img/photos/ca09.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/ca10.jpg", "label": "san bruno, ca, 2017"},
  {"url": "img/photos/ca11.jpg", "label": "devil's slide, ca, 2016"},
  {"url": "img/photos/ca12.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/ca13.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/ca14.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/ca15.jpg", "label": "san luis reservoir, ca, 2017"},
  {"url": "img/photos/ca16.jpg", "label": "rancho san antonio, ca, 2017"},
  {"url": "img/photos/ca17.jpg", "label": "san francisco international airport, ca, 2017"},
  {"url": "img/photos/ca18.jpg", "label": "san jose, ca, 2017"}
];