let images = [
  {"url": "img/photos/01.jpg", "label": "foster city, ca, 2017"},
  {"url": "img/photos/02.jpg", "label": "devil's slide, ca, 2017"},
  {"url": "img/photos/03.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/04.jpg", "label": "vineyard, ut, 2018"},
  {"url": "img/photos/05.jpg", "label": "richmond, va, 2017"},
  {"url": "img/photos/06.jpg", "label": "half moon bay, ca, 2017"},
  {"url": "img/photos/07.jpg", "label": "kingston, tn, 2018"},
  {"url": "img/photos/08.jpg", "label": "san carlos, ca, 2017"},
  {"url": "img/photos/09.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/12.jpg", "label": "barstow, ca, 2017"},
  {"url": "img/photos/13.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/14.jpg", "label": "devil's slide, ca, 2017"},
  {"url": "img/photos/16.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/23.jpg", "label": "hays, ks, 2018"},
  {"url": "img/photos/25.jpg", "label": "san mateo, ca, 2018"},
  {"url": "img/photos/31.jpg", "label": "williamsburg, va, 2017"},
  {"url": "img/photos/32.jpg", "label": "williamsburg, va, 2018"},
  {"url": "img/photos/41.jpg", "label": "richmond, va, 2017"},
  {"url": "img/photos/42.jpg", "label": "falls church, va, 2017"},
  {"url": "img/photos/45.jpg", "label": "richmond, va, 2017"},
  {"url": "img/photos/46.jpg", "label": "richmond, va, 2017"},
  {"url": "img/photos/47.jpg", "label": "crystal city, va, 2017"},
  {"url": "img/photos/49.jpg", "label": "richmond, va, 2017"},
  {"url": "img/photos/50.jpg", "label": "falls church, va, 2017"},
];
