let images = [
  {"url": "img/photos/wc/01.jpg", "label": "foster city, ca, 2017"},
  {"url": "img/photos/wc/02.jpg", "label": "devil's slide, ca, 2017"},
  {"url": "img/photos/wc/03.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/wc/04.jpg", "label": "san mateo, ca, 2018"},
  {"url": "img/photos/wc/05.jpg", "label": "san francsico, ca, 2017"},
  {"url": "img/photos/wc/06.jpg", "label": "half moon bay, ca, 2017"},
  {"url": "img/photos/wc/07.jpg", "label": "saratoga, ca, 2017"},
  {"url": "img/photos/wc/08.jpg", "label": "san carlos, ca, 2017"},
  {"url": "img/photos/wc/09.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/wc/10.jpg", "label": "cape kiwanda, or, 2017"},
  {"url": "img/photos/wc/11.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/wc/12.jpg", "label": "barstow, ca, 2017"},
  {"url": "img/photos/wc/13.jpg", "label": "san mateo, ca, 2017"},
  {"url": "img/photos/wc/14.jpg", "label": "devil's slide, ca, 2017"},
  {"url": "img/photos/wc/15.jpg", "label": "san carlos, ca, 2017"},
  {"url": "img/photos/wc/16.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/wc/17.jpg", "label": "san jose, ca, 2017"},
  {"url": "img/photos/wc/18.jpg", "label": "san bruno, ca, 2017"},
  {"url": "img/photos/wc/19.jpg", "label": "san francisco, ca, 2017"},
  {"url": "img/photos/wc/20.jpg", "label": "san francisco, ca, 2017"},
];